### ISSUE TITLE
cannot be installed

### ISSUE THREAD

**Issue by skardas** [privacy-scaling-explorations/maze#1]
since https://github.com/han0110/halo2-kzg-srs has got another commit, this repo cannot be installed.

if you use older rev, then it works like:

halo2_kzg_srs = { git = "https://github.com/han0110/halo2-kzg-srs", rev ="ff65429" }

**Comment by swjng** [comment]
I think this issue has been resolved, is that correct?

**Comment by swjng** [comment]
This issue is resolved in [this commit](https://github.com/privacy-scaling-explorations/maze/commit/f971459254db823fd58dacd88fb9760049587944)
