### ISSUE TITLE
dependencies are broken

### ISSUE THREAD

**Issue by snjax** [privacy-scaling-explorations/maze#3]
Dependency
```toml
halo2_proofs = { git = "https://github.com/han0110/halo2", branch = "feature/configurable-instance-query", package = "halo2_proofs" }
```
is broken, because currently there is no branch `feature/configurable-instance-query`  at [han0110/halo2](https://github.com/han0110/halo2).

**Comment by swjng** [comment]
Does it work now? Han's repository was not called in previous state, maybe you should run command `cargo update`. And also I fixed dependencies.

**Comment by snjax** [comment]
@jeong0982 now it is working.
